### ISSUE TITLE
Invalid acquisition of a currently held lock

### ISSUE THREAD

**Issue by alex-sherman** [Steffen-M/dotnet-ResourceAccessManager#5]
A lock can be acquired while it is being held be another execution context as long as it has been released at least once *but not completely* by the holder of the lock. Example:

```c#
static void Main(string[] args)
{
    // Task2 acquires the lock before Task1 releases it
    var t1 = task1();
    var t2 = task2();
    Task.WhenAll(t1, t2).GetAwaiter().GetResult();
    Console.ReadLine();
}
static async Task task1()
{
    var lock1 = await ResourceAccessManager.Default.AcquireExclusiveAccessAsync("other");
    using (lock1)
    {
        using (lock1) { }
        Console.WriteLine("Lock acquired");
        await Task.Delay(100);
    }
    Console.WriteLine("Lock released");
}
static async Task task2()
{
    await Task.Delay(50);
    using (await ResourceAccessManager.Default.AcquireExclusiveAccessAsync("other"))
    {
        Console.WriteLine("Lock acquired");
    }
    Console.WriteLine("Lock released");
}
```

**Comment by Steffen-M** [comment]
The issue is in the calling code in `task1()`. The second, inner `using` calls `Dispose()` on the `AccessHandle` `lock1` and releases the semaphore.
I see no way of catching bad usage of the API. I know, applying the "lambda pattern" would prevent a developer of such a misuse. But it comes with the cost of 1 or 2 additional async state machines.

**Comment by alex-sherman** [comment]
It's possible I'm just misunderstanding the API then, are the locks meant to be re-entrant or fully mutually exclusive?

**Comment by Steffen-M** [comment]
I'm not sure, what a re-entrant lock might be. Let me try to answer it in another way.
The RM is meant to facilitate scenarios, where a file is read into a DOM, then changed somehow, and then written back to disk. It might happen, that multiple threads/tasks are trying to access the same file at the same time. Without making these read/modify/write operations atomic, the last would win, hiding changes of the others. The responsibility of the RM is to acquire exclusive access to a file while doing these read/modify/write operations.
I know, using a DB would be the best choice here. But by intention files are used to give non-IT users an easy way to explore the data. It's not a productive implementation, rather than a mock implementation to provide transparent testing possibilities.
By the way, what are you trying to achieve with the inner `using`?
Thanks again for your commitment!
Steffen
